[osm.fields]
highway = "highway"
name = "name"
ref = "ref"
local_ref = "local_ref"
old_ref = "old_ref"
"destination:ref" = "destination_ref"

[major_road_labels]
ref_first = [
    "motorway",
    "motorway_link",
    "trunk",
    "trunk_link",
]

name_first = [
    "primary",
    "primary_link",
    "secondary",
    "secondary_link",
    "tertiary",
]

[minor_road_labels]
ref_first = []
name_first = [
    "tertiary",
    "unclassified",
    "residential",
    "service",
]

[road_abbreviations]
Alley = "Aly"
Avenue = "Ave"
Boulevard = "Blvd"
Circle = "Cir"
Court = "Ct"
Drive = "Dr"
Expressway = "Expy"
Highway = "Hwy"
Lane = "Ln"
Parkway = "Pkwy"
Place = "Pl"
Road = "Rd"
Street = "St"
Terrace = "Ter"
Trafficway = "Trfy"
Trail = "Trl"

[detail.green_areas]
landuse = [
    "grass",
    "meadow",
    "greenery",
    "flowerbed",
    "recreation_ground",
    "village_green",
    "forest",
]

natural = [
    "grassland",
    "shrubbery",
    "scrub",
    "heath",
    "wood",
]

leisure = [
    "park",
    "garden",
]

landcover = [
    "flowerbed",
]