[stations]
"NZ0F" = "COM-1"
"KC0DDZ-10" = "First Rider"
"AE0WC-10" = "SAG 4"
"K0RSE-13" = "TEC-50"
"KA2FNK-1" = "Troubleshooter"
"KD0EZD-9" = "SAG-2"
"KD0IDG-1" = "TEC-30"
"KE0CGR-5" = "VS-32"
"KE0LML-9" = "SAG-6"
"KE0NLN-9" = "VS-31"
"KE0VCD-9" = "VS-33"
"N0JCM-9" = "SAG-5"
"W0MAB-9" = "Moto 3"
"WA0BVX-9" = "Rover"
"WA0OFM-9" = "VS-34"
"KC4WCG-2" = "SAG-3"